# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee4a5efb79c293835a5dbde68523ef4153c3b30469166e0b29182e4ac2955660cdded7592199a42508c17166d0fa400b64435109c993b1e2abfd21a7b310e0c1

test:
  secret_key_base: 175766e052ac68e6fbc0c26dd303eb1ea87d6ba672e32ae4d405a00fcba9d8f42e5f1b4b13ead15ba09a6a2b65dd11222ba4c246a0f47b0e7e846087727eba07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
